'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useQueryClient } from '@tanstack/react-query';
import { useProjects, useCreateProject } from '@/hooks/use-projects';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Modal } from '@/components/ui/modal';
import { Loading } from '@/components/ui/loading';
import { ContextMenu, useContextMenu } from '@/components/ui/context-menu';
import Link from 'next/link';
import toast from 'react-hot-toast';

interface DashboardClientProps {
  userId: string;
  organizationId?: string;
}

const looksLikeAutoGeneratedId = (value: string) => {
  const compact = value.replace(/[^a-z0-9]/gi, '');
  if (!compact) return true;
  const hasLetters = /[a-z]/i.test(compact);
  if (!hasLetters && compact.length >= 6) return true;
  if (/^\d{6,}$/.test(compact)) return true;
  if (compact.length >= 24 && !value.includes(' ')) return true;
  return false;
};

// Helper function to generate project name from URL
function generateProjectNameFromUrl(url: string): string {
  try {
    const urlObj = new URL(url);
    // Extract the last meaningful part of the path
    const pathParts = urlObj.pathname.split('/').filter(Boolean);
    const lastPart = pathParts[pathParts.length - 1] || urlObj.hostname;

    // Clean up the name: replace dashes/underscores with spaces, remove file extensions
    let name = lastPart
      .replace(/[-_]/g, ' ')
      .replace(/\.(html|htm|php|aspx|jsp)/i, '')
      .trim();

    // Capitalize first letter of each word
    name = name
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ');

    // If name is too short, generic, or looks auto-generated, use hostname
    if (
      name.length < 3 ||
      name.toLowerCase() === 'product' ||
      name.toLowerCase() === 'item' ||
      looksLikeAutoGeneratedId(lastPart)
    ) {
      const hostBase = urlObj.hostname.replace('www.', '').split('.')[0];
      const brand = hostBase.charAt(0).toUpperCase() + hostBase.slice(1);
      name = `${brand} Product`;
    }

    return name || 'New Project';
  } catch {
    // If URL parsing fails, try to extract from string
    const parts = url.split('/').filter(Boolean);
    const lastPart = parts[parts.length - 1] || 'Product';
    return lastPart
      .replace(/[-_]/g, ' ')
      .replace(/\.(html|htm|php|aspx|jsp)/i, '')
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ') || 'New Project';
  }
}

// Helper function to format project creation date
function formatProjectDate(createdAt: Date | string): string {
  const createdDate = new Date(createdAt);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const projectDate = new Date(createdDate.getFullYear(), createdDate.getMonth(), createdDate.getDate());

  // If the project was created today, show date and time
  if (projectDate.getTime() === today.getTime()) {
    return `Created today at ${createdDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  }

  // Otherwise, just show the date
  return `Created ${createdDate.toLocaleDateString()}`;
}

export function DashboardClient({ userId, organizationId }: DashboardClientProps) {
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [isRenameModalOpen, setIsRenameModalOpen] = useState(false);
  const [renameValue, setRenameValue] = useState('');
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null);
  const [productUrl, setProductUrl] = useState('');
  const [flowType, setFlowType] = useState<'manual' | 'automatic'>('manual');
  const [createStep, setCreateStep] = useState<'flow' | 'url' | 'stream'>('flow');
  const [statusItems, setStatusItems] = useState<
    { id: string; label: string; state: 'pending' | 'success' | 'error' }[]
  >([]);
  const [isStreaming, setIsStreaming] = useState(false);
  const router = useRouter();
  const queryClient = useQueryClient();
  const contextMenu = useContextMenu();

  // Use provided organizationId or fall back to default
  const activeOrganizationId = organizationId || 'default-org';

  const { data: projects, isLoading } = useProjects(activeOrganizationId);
  const createProject = useCreateProject();

  const handleOpenRename = (projectId: string, currentName: string) => {
    setSelectedProjectId(projectId);
    setRenameValue(currentName);
    setIsRenameModalOpen(true);
  };

  const handleRenameProject = async () => {
    if (!selectedProjectId || !renameValue.trim()) {
      toast.error('Project name is required');
      return;
    }
    try {
      const response = await fetch(`/api/projects/${selectedProjectId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'rename', name: renameValue.trim() }),
      });
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to rename project');
      }
      toast.success('Project renamed');
      setIsRenameModalOpen(false);
      queryClient.invalidateQueries({ queryKey: ['projects', activeOrganizationId] });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to rename project');
    }
  };

  const handleArchiveProject = async (projectId: string) => {
    try {
      const response = await fetch(`/api/projects/${projectId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'archive' }),
      });
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Failed to archive project');
      }
      toast.success('Project archived');
      queryClient.invalidateQueries({ queryKey: ['projects', activeOrganizationId] });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to archive project');
    }
  };

  const resetCreateModal = () => {
    setIsCreateModalOpen(false);
    setProductUrl('');
    setFlowType('manual');
    setCreateStep('flow');
    setStatusItems([]);
    setIsStreaming(false);
  };

  const addStatus = (label: string) => {
    const id = `status-${Date.now()}-${Math.random().toString(16).slice(2)}`;
    setStatusItems((items) => [...items, { id, label, state: 'pending' }]);
    return id;
  };

  const updateStatus = (id: string, state: 'pending' | 'success' | 'error', label?: string) => {
    setStatusItems((items) =>
      items.map((item) => (item.id === id ? { ...item, state, label: label ?? item.label } : item))
    );
  };

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!productUrl.trim() || !activeOrganizationId) return;

    // Validate URL format
    try {
      new URL(productUrl);
    } catch {
      toast.error('Please enter a valid URL');
      return;
    }

    // Generate project name from URL
    const projectName = generateProjectNameFromUrl(productUrl);

    setCreateStep('stream');
    setIsStreaming(true);
    setStatusItems([]);

    const createStatusId = addStatus('Creating your project...');

    try {
      const result = await createProject.mutateAsync({
        name: projectName,
        organizationId: activeOrganizationId,
        productUrl: productUrl,
        flowType: flowType,
      });

      const projectId = result?.project?.id;
      if (!projectId) {
        updateStatus(createStatusId, 'error', 'Project creation failed');
        setIsStreaming(false);
        return;
      }

      updateStatus(createStatusId, 'success', 'Project created');

      const extractStatusId = addStatus('Extracting product information...');
      try {
        const extractResponse = await fetch(`/api/projects/${projectId}/product`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: productUrl }),
        });

        if (!extractResponse.ok) {
          const error = await extractResponse.json();
          updateStatus(
            extractStatusId,
            'error',
            error.error || 'Failed to extract product details'
          );
          toast.error(error.error || 'Failed to extract product details');
          setIsStreaming(false);
          return;
        }

        const extractedData = await extractResponse.json();
        updateStatus(extractStatusId, 'success', 'Product details extracted');

        if (extractedData?.product?.name) {
          const nameStatusId = addStatus(`Product name detected: ${extractedData.product.name}`);
          updateStatus(nameStatusId, 'success');
        }
      } catch (error) {
        updateStatus(extractStatusId, 'error', 'Failed to extract product details');
        toast.error('Failed to extract product details');
        setIsStreaming(false);
        return;
      }

      if (flowType === 'automatic') {
        const autoStatusId = addStatus('Running auto-generation pipeline...');
        try {
          const autoResponse = await fetch(`/api/projects/${projectId}/auto-generate`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ style: 'energetic' }),
          });

          if (!autoResponse.ok) {
            const error = await autoResponse.json();
            updateStatus(
              autoStatusId,
              'error',
              error.error || 'Auto-generation failed'
            );
            toast.error(error.error || 'Auto-generation failed');
            setIsStreaming(false);
            return;
          }

          const autoData = await autoResponse.json();
          updateStatus(autoStatusId, 'success', 'Auto-generation completed');

          if (typeof autoData?.scenes === 'number') {
            const scenesStatusId = addStatus(`Scenes generated: ${autoData.scenes}`);
            updateStatus(scenesStatusId, 'success');
          }

          if (typeof autoData?.images === 'number') {
            const imagesStatusId = addStatus(`Images generated: ${autoData.images}`);
            updateStatus(imagesStatusId, 'success');
          }

          if (autoData?.voiceover?.url) {
            const voiceStatusId = addStatus('Voiceover generated');
            updateStatus(voiceStatusId, 'success');
          }
        } catch (error) {
          updateStatus(autoStatusId, 'error', 'Auto-generation failed');
          toast.error('Auto-generation failed');
          setIsStreaming(false);
          return;
        }
      }

      const finalStatusId = addStatus('Finalizing your workspace...');
      updateStatus(finalStatusId, 'success', 'All set. Opening your project...');
      setIsStreaming(false);

      setTimeout(() => {
        resetCreateModal();
        router.push(`/projects/${projectId}`);
      }, 700);
    } catch (error) {
      updateStatus(createStatusId, 'error', 'Project creation failed');
      console.error('Failed to create project:', error);
      setIsStreaming(false);
    }
  };

  return (
    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Your Projects</h2>
          <p className="mt-1 text-sm text-muted">
            Create and manage your video ad projects
          </p>
        </div>
        <Button
          onClick={() => {
            setIsCreateModalOpen(true);
            setCreateStep('flow');
            setStatusItems([]);
          }}
        >
          <svg
            className="mr-2 h-5 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 4v16m8-8H4"
            />
          </svg>
          New Project
        </Button>
      </div>

      {isLoading ? (
        <div className="flex h-64 items-center justify-center">
          <Loading size="lg" text="Loading projects..." />
        </div>
      ) : projects && projects.length > 0 ? (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {projects.map((project) => (
            <Link
              key={project.id}
              href={`/projects/${project.id}`}
              className="group block rounded-xl border border-border bg-surface p-6 shadow-sm transition-all hover:border-brand/40 hover:shadow-md"
              onContextMenu={(event) => {
                setSelectedProjectId(project.id);
                contextMenu.open(event);
              }}
            >
              <div className="mb-4 flex items-start justify-between">
                <h3 className="text-lg font-semibold text-foreground group-hover:text-brand">
                  {project.name}
                </h3>
                <span className="rounded-full bg-brand-100 px-2 py-1 text-xs font-medium text-brand-700">
                  {project.currentStep}
                </span>
              </div>
              <p className="text-sm text-muted">
                {formatProjectDate(project.createdAt)}
              </p>
              <div className="mt-4 flex items-center text-sm text-brand">
                Continue editing
                <svg
                  className="ml-1 h-4 w-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9 5l7 7-7 7"
                  />
                </svg>
              </div>
            </Link>
          ))}
        </div>
      ) : (
        <div className="flex h-64 flex-col items-center justify-center rounded-xl border-2 border-dashed border-border bg-surface">
          <svg
            className="h-12 w-12 text-subtle"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
            />
          </svg>
          <h3 className="mt-4 text-lg font-medium text-foreground">No projects yet</h3>
          <p className="mt-2 text-sm text-muted text-center max-w-md">
            Get started by creating your first video ad project. You can manage your organization and team members in the settings.
          </p>
          <div className="mt-6 flex gap-3">
            <Button
              onClick={() => {
                setIsCreateModalOpen(true);
                setCreateStep('flow');
                setStatusItems([]);
              }}
            >
              Create Project
            </Button>
            <Link href="/settings/organizations">
              <Button variant="outline">
                Manage Organization
              </Button>
            </Link>
          </div>
        </div>
      )}

      <ContextMenu
        items={[
          {
            id: 'rename',
            label: 'Rename',
            onSelect: () => {
              const project = projects?.find((item) => item.id === selectedProjectId);
              if (project) {
                handleOpenRename(project.id, project.name);
              }
            },
          },
          {
            id: 'archive',
            label: 'Archive',
            tone: 'danger',
            onSelect: () => {
              if (selectedProjectId) {
                handleArchiveProject(selectedProjectId);
              }
            },
          },
        ]}
        position={contextMenu.position}
        onClose={contextMenu.close}
      />

      <Modal
        isOpen={isRenameModalOpen}
        onClose={() => {
          setIsRenameModalOpen(false);
        }}
        title="Rename Project"
      >
        <div className="space-y-4">
          <Input
            label="Project Name"
            value={renameValue}
            onChange={(e) => setRenameValue(e.target.value)}
            placeholder="Enter project name"
            autoFocus
          />
          <div className="flex justify-end gap-3">
            <Button variant="outline" onClick={() => setIsRenameModalOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleRenameProject}>Save</Button>
          </div>
        </div>
      </Modal>

      <Modal
        isOpen={isCreateModalOpen}
        onClose={() => {
          if (isStreaming) return;
          resetCreateModal();
        }}
        title="Create New Project"
      >
        {createStep === 'flow' && (
          <div className="space-y-5">
            <div>
              <h3 className="text-base font-semibold text-foreground">
                Would you like to create them video ad manually or have the system create it
                automatically?
              </h3>
              <p className="mt-1 text-sm text-subtle">
                Choose how hands-on you want to be as we build your first cut.
              </p>
            </div>
            <div role="radiogroup" className="grid gap-3 sm:grid-cols-2">
              <button
                type="button"
                role="radio"
                aria-checked={flowType === 'manual'}
                onClick={() => setFlowType('manual')}
                className={`flex h-full w-full items-start gap-4 rounded-2xl border px-4 py-5 text-left transition-all ${
                  flowType === 'manual'
                    ? 'border-brand/60 bg-brand-50 shadow-md shadow-brand/10'
                    : 'border-border bg-surface hover:border-brand/40'
                }`}
              >
                <span
                  className={`mt-1 flex h-7 w-7 items-center justify-center rounded-full border ${
                    flowType === 'manual'
                      ? 'border-brand bg-brand text-white'
                      : 'border-border text-subtle'
                  }`}
                >
                  {flowType === 'manual' ? '✓' : '•'}
                </span>
                <div>
                  <span className="text-base font-semibold text-foreground">Manual Flow</span>
                  <p className="mt-1 text-sm text-subtle">
                    Full control with step-by-step inputs and approvals.
                  </p>
                </div>
              </button>
              <button
                type="button"
                role="radio"
                aria-checked={flowType === 'automatic'}
                onClick={() => setFlowType('automatic')}
                className={`flex h-full w-full items-start gap-4 rounded-2xl border px-4 py-5 text-left transition-all ${
                  flowType === 'automatic'
                    ? 'border-brand/60 bg-brand-50 shadow-md shadow-brand/10'
                    : 'border-border bg-surface hover:border-brand/40'
                }`}
              >
                <span
                  className={`mt-1 flex h-7 w-7 items-center justify-center rounded-full border ${
                    flowType === 'automatic'
                      ? 'border-brand bg-brand text-white'
                      : 'border-border text-subtle'
                  }`}
                >
                  {flowType === 'automatic' ? '✓' : '•'}
                </span>
                <div>
                  <span className="text-base font-semibold text-foreground">Automatic Flow</span>
                  <p className="mt-1 text-sm text-subtle">
                    Let the system generate the full first draft automatically.
                  </p>
                </div>
              </button>
            </div>
            <div className="flex justify-end gap-3">
              <Button type="button" variant="outline" onClick={resetCreateModal}>
                Cancel
              </Button>
              <Button type="button" onClick={() => setCreateStep('url')}>
                Continue
              </Button>
            </div>
          </div>
        )}
        {createStep === 'url' && (
          <form onSubmit={handleCreateProject} className="space-y-4">
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-subtle">
              Selected flow
              <span className="rounded-full bg-brand-100 px-2 py-0.5 text-[11px] font-medium text-brand-700">
                {flowType === 'manual' ? 'Manual' : 'Automatic'}
              </span>
            </div>
            <div>
              <Input
                label="Product URL"
                type="url"
                value={productUrl}
                onChange={(e) => setProductUrl(e.target.value)}
                placeholder="https://example.com/products/your-item"
                required
                autoFocus
              />
              <p className="mt-1 text-sm text-subtle">
                Paste the URL of the product you want to create an ad for. We'll automatically name your project.
              </p>
            </div>
            <div className="flex justify-between gap-3">
              <Button type="button" variant="outline" onClick={() => setCreateStep('flow')}>
                Back
              </Button>
              <Button type="submit" isLoading={createProject.isPending}>
                Start
              </Button>
            </div>
          </form>
        )}
        {createStep === 'stream' && (
          <div className="space-y-4">
            <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-slate-950/70 p-6 text-white shadow-2xl shadow-slate-950/40 backdrop-blur-2xl">
              <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-brand/25 via-transparent to-fuchsia-500/20" />
              <div className="pointer-events-none absolute -left-10 -top-10 h-32 w-32 rounded-full bg-brand/30 blur-3xl" />
              <div className="pointer-events-none absolute -bottom-12 -right-12 h-40 w-40 rounded-full bg-fuchsia-500/20 blur-3xl" />
              <div className="relative space-y-4">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/60">
                    Streaming overlay
                  </p>
                  <h3 className="mt-2 text-2xl font-semibold text-white">
                    Generating your project
                  </h3>
                  <p className="mt-1 text-sm text-white/70">
                    Sit tight while we build your project. This may take a minute.
                  </p>
                </div>
                <div className="relative h-56 overflow-hidden rounded-2xl border border-white/10 bg-white/5 px-4 py-3 backdrop-blur">
                  <div className="pointer-events-none absolute inset-x-0 top-0 h-12 bg-gradient-to-b from-slate-950/60 to-transparent" />
                  <div className="pointer-events-none absolute inset-x-0 bottom-0 h-12 bg-gradient-to-t from-slate-950/60 to-transparent" />
                  <div className="flex h-full flex-col justify-end gap-2">
                    {statusItems.map((item) => (
                      <div key={item.id} className="flex items-start gap-2 text-xs text-white/80">
                        <span
                          className={`mt-1 h-2 w-2 rounded-full ${
                            item.state === 'success'
                              ? 'bg-emerald-400'
                              : item.state === 'error'
                              ? 'bg-red-400'
                              : 'bg-brand/80 animate-pulse'
                          }`}
                        />
                        <span
                          className={`font-mono ${
                            item.state === 'error'
                              ? 'text-red-300'
                              : item.state === 'success'
                              ? 'text-white'
                              : 'text-white/70'
                          }`}
                        >
                          {item.label}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
            {!isStreaming && (
              <div className="flex justify-end gap-3">
                <Button type="button" variant="outline" onClick={() => setCreateStep('url')}>
                  Back
                </Button>
                <Button type="button" onClick={resetCreateModal}>
                  Close
                </Button>
              </div>
            )}
          </div>
        )}
      </Modal>
    </main>
  );
}
